services:
  db:
    image: postgres:15-alpine
    container_name: postgres-adocao
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SenhaSQL
      POSTGRES_DB: projeto_adocao
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: