spring.application.name=Projeto_Adocao
# Configurações do Banco de Dados Postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/project_adocao
spring.datasource.username=postgres
spring.datasource.password=SenhaSql

server.error.include-stacktrace=never

api.security.token.secret=${JWT_Secret:3241}

logging.level.org.springframework.security=DEBUG