spring:
  application:
    name: Projeto_Adocao
  datasource:
    # Configuracoes do Banco de Dados Postgresql
    url: jdbc:postgresql://localhost:5433/projeto_adocao
    username: postgres
    password: SenhaSQL

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_Secret:3241}

logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html